export const appPath = {
	notFound: "*",
	default: "/",
	home: "/home",
	studentDashboard: "/studentdashboard",
	teacherDashboard: "/teacherdashboard",
	adminDashboard: "admindashboard",
	studentList: "/studentlist",
	studentView: "/studentview",
	studentAdd: "/studentadd",
	studentEdit: "/studentedit",
	teacherList: "/teacherlist",
	teacherView: "/teacherview",
	teacherAdd: "/teacheradd",
	teacherEdit: "/teacheredit",
	departmentList: "/departmentlist",
	departmentAdd: "/departmentadd",
	departmentEdit: "/departmentedit",
	subjectList: "/subjectlist",
	subjectAdd: "/subjectadd",
	subjectEdit: "/subjectedit",
	examList: "/examlist",
	timeTable: "/timetable",
	library: "/library",
	allBlogs: "/allblogs",
	addBlog: "/addblog",
	editBlog: "/editblog",
};
